name: FLUTTER-CI

on:
  push:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
      - uses: ozaytsev86/create-env-file@v1
        with:
          ENV_OPEN_WEATHER_KEY: ${{ secrets.OPEN_WEATHER_KEY }}
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
  unit-test:
    runs-on: ubuntu-latest
    needs: [analyze]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
      - uses: ozaytsev86/create-env-file@v1
        with:
          ENV_OPEN_WEATHER_KEY: ${{ secrets.OPEN_WEATHER_KEY }}
      - run: flutter pub get
      - run: flutter test
  ui-test:
    runs-on: macos-latest
    needs: [analyze]
    strategy:
      matrix:
        api-level: [21]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
      - uses: ozaytsev86/create-env-file@v1
        with:
          ENV_OPEN_WEATHER_KEY: ${{ secrets.OPEN_WEATHER_KEY }}
      - run: flutter pub get
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: flutter test integration_test
          arch: x86_64
          profile: pixel
  deploy:
    runs-on: ubuntu-latest
    needs: [unit-test, ui-test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
      - uses: ozaytsev86/create-env-file@v1
        with:
          ENV_OPEN_WEATHER_KEY: ${{ secrets.OPEN_WEATHER_KEY }}
      - run: flutter pub get
      - run: flutter build apk
      - uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/apk/release/app-release.apk
          tag_name: "v1.0.0"
