name: FLUTTER-CI

on:
  push:
    branches:
      - dev-ci

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29]
        target: [default]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
      - uses: ozaytsev86/create-env-file@v1
        with:
          ENV_OPEN_WEATHER_KEY: ${{ secrets.OPEN_WEATHER_KEY }}
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter test
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          script: flutter test integration_test
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
      - run: flutter analyze .
      - run: flutter build apk
      - uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/apk/release/app-release.apk
          tag_name: "v1.0.0"
